# services:
#   react-app:
#     build: .
#     ports:
#       - "5173:5173"  # <-- Porta correta do Vite
#     volumes:
#       - ./my-react-app:/app
#     working_dir: /app
#     command: >
#       sh -c "if [ ! -f package.json ]; then
#                npm create vite@latest . -- --template react &&
#                npm install;
#              fi &&
#              npm run dev -- --host 0.0.0.0"
#     environment:
#       - CHOKIDAR_USEPOLLING=true


# services:
#   react-app:
#     container_name: prime
#     build: .
#     ports:
#       - "5173:5173" # Porta externa 5174 mapeia para a interna 5173
#     volumes:
#       - ./prime:/app
#     working_dir: /app
#     command: >
#       sh -c "if [ ! -f package.json ]; then
#                npm create vite@latest . -- --template react &&
#                npm install &&
#                npm install react-router-dom axios;
#              fi &&
#              npm run dev -- --host 0.0.0.0"
#     environment:
#       - CHOKIDAR_USEPOLLING=true


services:
  react-app:
    container_name: prime
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./prime:/app
    working_dir: /app
    command: >
      sh -c "if [ ! -f package.json ]; then
               npm create vite@latest . -- --template react &&
               npm install react-router-dom axios;
             else
               npm install;
             fi &&
             npm run dev -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true
